language: python
python:
  - 3.6
services:
  - sqlite
env:
  - DJANGO=2.0 DB=sqlite
install:
  - python3 -m pip install --upgrade .
before_script:
  - cp taxibros/settings/local_settings.py.template taxibros/settings/local_settings.py
  - python3 manage.py makemigrations
  - python3 manage.py migrate --run-syncdb
  - python3 manage.py runserver &
script:
  - coverage run manage.py test
